name: reprobench
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12=py_0
  - anaconda-client=1.7.2=py_0
  - ansimarkup=1.4.0=py_0
  - ansiwrap=0.8.4=py_0
  - appnope=0.1.0=py37_1000
  - apsw=3.25.2.r1=py37hb402a30_1000
  - asn1crypto=0.24.0=py37_1003
  - attrs=19.1.0=py_0
  - babel=2.7.0=py_0
  - backcall=0.1.0=py_0
  - backports=1.0=py_2
  - backports.tempfile=1.0=py_0
  - backports.weakref=1.0.post1=py37_1000
  - bcrypt=3.1.6=py37h01d97ff_1
  - beautifulsoup4=4.7.1=py37_1001
  - better_exceptions_fork=0.2.1.post6=py_0
  - bleach=3.1.0=py_0
  - bzip2=1.0.6=h1de35cc_1002
  - ca-certificates=2019.6.16=hecc5488_0
  - certifi=2019.6.16=py37_1
  - cffi=1.12.3=py37hccf1714_0
  - chardet=3.0.4=py37_1003
  - click=7.0=py_0
  - clyent=1.2.2=py_1
  - colorama=0.4.1=py_0
  - conda=4.6.14=py37_0
  - conda-build=3.18.7=py37_1
  - conda-package-handling=1.3.11=py37_0
  - conda-verify=3.1.1=py37_1000
  - cryptography=2.6.1=py37h212c5bf_0
  - cycler=0.10.0=py_1
  - dbus=1.13.6=h2f22bb5_0
  - decorator=4.4.0=py_0
  - defusedxml=0.5.0=py_1
  - docutils=0.14=py37_1001
  - entrypoints=0.3=py37_1000
  - expat=2.2.5=h0a44026_1002
  - filelock=3.0.10=py_0
  - freetype=2.10.0=h24853df_0
  - future=0.17.1=py37_1000
  - gettext=0.19.8.1=h46ab8bc_1002
  - gevent=1.4.0=py37h470a237_0
  - glib=2.58.3=h2836805_1001
  - glob2=0.6=py_0
  - greenlet=0.4.15=py37h01d97ff_0
  - icu=58.2=h0a44026_1000
  - idna=2.8=py37_1000
  - imagesize=1.1.0=py_0
  - ipykernel=5.1.1=py37h24bf2e0_0
  - ipython=7.5.0=py37h24bf2e0_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.4.2=py_0
  - jedi=0.13.3=py37_0
  - jinja2=2.10.1=py_0
  - jpeg=9c=h1de35cc_1001
  - jsonschema=3.0.1=py37_0
  - jupyter=1.0.0=py_2
  - jupyter_client=5.2.4=py_3
  - jupyter_console=6.0.0=py_0
  - jupyter_core=4.4.0=py_0
  - kiwisolver=1.1.0=py37h770b8ee_0
  - leveldb=1.18=0
  - libarchive=3.3.3=h46c8594_1004
  - libblas=3.8.0=10_openblas
  - libcblas=3.8.0=10_openblas
  - libcxx=8.0.0=2
  - libcxxabi=8.0.0=2
  - libffi=3.2.1=h6de7cb9_1006
  - libgfortran=3.0.1=0
  - libiconv=1.15=h01d97ff_1005
  - liblapack=3.8.0=10_openblas
  - liblief=0.9.0=h2a1bed3_1
  - libopenblas=0.3.6=hd44dcd8_4
  - libpng=1.6.37=h2573ce8_0
  - libsodium=1.0.16=h1de35cc_1001
  - libxml2=2.9.9=hd80cff7_0
  - loguru=0.2.5=py_0
  - lz4-c=1.8.3=h6de7cb9_1001
  - lzo=2.10=h1de35cc_1000
  - markupsafe=1.1.1=py37h1de35cc_0
  - matplotlib-base=3.1.0=py37h3a684a6_1
  - mistune=0.8.4=py37h1de35cc_1000
  - msgpack-python=0.6.1=py37h04f5b5a_0
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py_1
  - ncurses=6.1=h0a44026_1002
  - notebook=5.7.8=py37_1
  - numpy=1.16.3=py37hdf140aa_0
  - openblas=0.3.6=hd44dcd8_4
  - openssl=1.1.1c=h01d97ff_0
  - packaging=19.0=py_0
  - pandas=0.24.2=py37h0a44026_0
  - pandoc=2.7.2=0
  - pandocfilters=1.4.2=py_1
  - papermill=1.0.0=py37_0
  - paramiko=2.5.0=py37_0
  - parso=0.4.0=py_0
  - pathspec=0.5.9=py_0
  - patsy=0.5.1=py_0
  - pcre=8.41=h0a44026_1003
  - peewee=3.9.2=py37hb402a30_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_1000
  - pip=19.1=py37_0
  - pkginfo=1.5.0.1=py_0
  - prometheus_client=0.7.0=py_0
  - prompt_toolkit=2.0.9=py_0
  - psutil=5.6.2=py37h01d97ff_0
  - ptyprocess=0.6.0=py_1001
  - py-cpuinfo=5.0.0=py_0
  - py-lief=0.9.0=py37h6d6d4d2_1
  - pycosat=0.6.3=py37h1de35cc_1001
  - pycparser=2.19=py37_1
  - pygments=2.4.0=py_0
  - pynacl=1.3.0=py37h1de35cc_1000
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.0=py_0
  - pyqt=5.9.2=py37h2a560b1_0
  - pyrsistent=0.15.2=py37h01d97ff_0
  - pysocks=1.7.0=py37_0
  - python=3.7.3=h0d93f26_0
  - python-dateutil=2.8.0=py_0
  - python-leveldb=0.194=py37h6de7cb9_1000
  - python-libarchive-c=2.8=py37_1004
  - pytz=2019.1=py_0
  - pyyaml=5.1=py37h1de35cc_0
  - pyzmq=18.0.1=py37h2d07e9b_1
  - qt=5.9.7=h93ee506_1
  - qtconsole=4.5.1=py_0
  - readline=7.0=hcfe32e1_1001
  - requests=2.22.0=py37_0
  - retrying=1.3.3=py_2
  - ruamel=1.0=py37_0
  - ruamel.yaml=0.15.96=py37h01d97ff_0
  - ruamel_yaml=0.15.71=py37h1de35cc_1000
  - scipy=1.3.0=py37hab3da7d_0
  - seaborn=0.9.0=py_1
  - send2trash=1.5.0=py_0
  - setuptools=41.0.1=py37_0
  - sip=4.19.8=py37h0a44026_1000
  - six=1.12.0=py37_1000
  - snappy=1.1.7=h0a44026_1002
  - snowballstemmer=1.2.1=py_1
  - soupsieve=1.9.1=py37_0
  - sphinx=2.1.1=py_0
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.1=py_0
  - sqlite=3.28.0=h9721f7c_0
  - statsmodels=0.9.0=py37h917ab60_1000
  - strictyaml=1.0.1=py_0
  - tenacity=5.0.4=py37_0
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py_1001
  - textwrap3=0.9.2=py_0
  - tk=8.6.9=ha441bb4_1001
  - tornado=6.0.2=py37h01d97ff_0
  - tqdm=4.32.1=py_0
  - traitlets=4.3.2=py37_1000
  - urllib3=1.24.3=py37_0
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.33.4=py37_0
  - widgetsnbextension=3.4.2=py37_1000
  - xz=5.2.4=h1de35cc_1001
  - yaml=0.1.7=h1de35cc_1001
  - zeromq=4.3.1=h0a44026_1000
  - zlib=1.2.11=h1de35cc_1004
  - zstd=1.3.3=1
  - pip:
    - configspace==0.4.10
    - cython==0.29.7
    - livereload==2.6.1
    - psmon==1.1.1
    - reprobench==0.11.0.dev13
    - sphinx-reload==0.2.0
    - sphinx-rtd-theme==0.4.3
    - sshtunnel==0.1.5
    - typing==3.6.6
prefix: /Users/rkkautsar/.pyenv/versions/miniconda3-4.3.30/envs/reprobench
